version: '3'
services:
  client:
    build:
      context: client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/home/node/app
    ports:
      - 3000:3000
    command: [yarn, start]
    environment:
      - NODE_ENV
